utils.localNotepadNamePattern=${LOCAL_NOTEPAD_NAME_PATTERN}
utils.localExcelNamePattern=${LOCAL_EXCEL_NAME_PATTERN}
utils.localPath=${LOCAL_PATH}

utils.remoteNotepadNamePattern=${REMOTE_NOTEPAD_NAME_PATTERN}
utils.remoteExcelNamePattern=${REMOTE_EXCEL_NAME_PATTERN}
utils.remotePath=${REMOTE_PATH}

utils.sftpHost=${SFTP_HOST}
utils.sftpPort=${SFTP_PORT}
utils.sftpUser=${SFTP_USERNAME}
utils.sftpPassword=${SFTP_PASSWORD}

utils.gestorUsuarioServiceUrl=${GESTOR_USUARIO_SERVICE_URL}
