utils.localNotepadName=${LOCAL_NOTEPAD_NAME}
utils.localExcelName=${LOCAL_EXCEL_NAME}
utils.localPath=${LOCAL_PATH}

utils.remoteNotepadName=${REMOTE_NOTEPAD_NAME}
utils.remoteExcelName=${REMOTE_EXCEL_NAME}
utils.remotePath=${REMOTE_PATH}

utils.gestorUsuarioServiceUrl=${GESTOR_USUARIO_SERVICE_URL}